# Generated by Django 5.2.1 on 2025-06-04 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
    ]
